apiVersion: apps/v1
kind: Deployment
metadata: 
  name: analytics-deployment
  labels: 
    app.kubernetes.io/part-of: application-1
    app.kubernetes.io/name: analytics
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: user-analytics
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/part-of: application-1
      app.kubernetes.io/name: analytics
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: user-analytics
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: application-1
        app.kubernetes.io/name: analytics
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: user-analytics
    spec:
      containers:
        - name: analytics
          image: nginx:1.7.9
          ports:
            - containerPort: 80
